Refactoring the component to use the new token structure
selsa-inube/inubekit-spinner pull request #3
Opened 2024-02-22 15:29 UTC by JanuarAsprilla

this card refactors the component to use the new token structure

2024-02-22 23:12 UTC, JanuarAsprilla commented on src/Spinner/styles.js
> +export const animationspinner = keyframes`
solved

2024-02-23 17:12 UTC, cmarin001 approved these changes
meet the requirements

2024-02-23 20:41 UTC, wfercanas requested changes

2024-02-23 20:41 UTC, wfercanas commented on package.json
> +    "@inubekit/foundations": "^2.2.1",
@inubekit/foundations va en dependencies

2024-02-23 20:41 UTC, wfercanas commented on src/Spinner/index.tsx
>  export interface ISpinnerProps {
Change name to ISpinner

2024-02-23 20:41 UTC, wfercanas commented on src/Spinner/props.ts
> +export const Appearance = Object.keys(inube.spinner);
Con Object.keys() saca las appearances, pero eso es apenas un array. Hace falta que cree en `type`.

Le sugiero que más bien cree el array `appearances` de forma literal y defina ese array `as const` tal como hizo con `sizes`. Luego crear el tipo es cuestión de repetir lo que hizo en el `type Size`.

2024-02-23 20:41 UTC, wfercanas commented on src/Spinner/props.ts
> +    options: Appearance,
Aquí iría appearances el array, no Appearance el type.

2024-02-23 20:41 UTC, wfercanas commented on src/Spinner/styles.js
> +    $appearance && $transparent
No probemos si appearance está definido.

2024-02-23 20:41 UTC, wfercanas commented on src/Spinner/styles.js
>      $transparent === true
Aquí está probando `$transparent === true` y abajo sólo `$transparent`. Estandarice y use una sola forma.

2024-02-23 20:49 UTC, JanuarAsprilla commented on package.json
> +    "@inubekit/foundations": "^2.2.1",
corregido

2024-02-23 20:49 UTC, JanuarAsprilla commented on src/Spinner/index.tsx
>  export interface ISpinnerProps {
solved

2024-02-23 20:57 UTC, JanuarAsprilla commented on src/Spinner/styles.js
> +    $appearance && $transparent
corregido

2024-02-23 21:07 UTC, JanuarAsprilla commented on src/Spinner/props.ts
> +export const Appearance = Object.keys(inube.spinner);
corregido

2024-02-26 15:01 UTC, cmarin001 approved these changes
meet the requirements

2024-02-26 17:25 UTC, wfercanas commented on src/Spinner/props.ts
> +    options: Appearance,
El array debería ser `appearances` en plural

2024-02-27 15:55 UTC, wfercanas approved these changes

2024-02-27 15:55 UTC, merged